---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: db
    application: db-service
    system: springboot-sample
  name: db-config
data:
  POSTGRESQL_DATABASE: cG9zdGdyZXM=
  POSTGRESQL_USERNAME: cG9zdGdyZXM=
  POSTGRESQL_PASSWORD: cG9zdGdyZXM=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: rest-db
    application: db-service
    system: springboot-sample
  name: rest-db-config-creds
data:
  spring.datasource.username: cG9zdGdyZXM=
  spring.datasource.password: cG9zdGdyZXM=
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: db
    application: db-service
    system: springboot-sample
  name: db-init
data:
  get-data.sh: |-
    #!/bin/bash

    curl https://github.com/NaotoDoujun/springboot_sample/blob/main/rest-db/src/main/resources/data.sql --output /docker-entrypoint-initdb.d/1-init-tables.sql
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rest-db
    application: db-service
    system: springboot-sample
  name: rest-db-config
data:
  spring.profiles.active: production
  spring.datasource.url: jdbc:postgresql://db:5432/postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rest-git
    application: git-service
    system: springboot-sample
  name: rest-git-config
data:
  spring.profiles.active: production
  storage.remoteurl: https://github.com/NaotoDoujun/springboot_sample.git
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rest-backend
    application: backend-service
    system: springboot-sample
  name: rest-backend-config
data:
  spring.profiles.active: production
  rest.db.endpoint: http://rest-db:8081
  rest.git.endpoint: http://rest-git:8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ui-frontend
    application: frontend
    system: springboot-sample
  name: ui-frontend-config
data:
  spring.profiles.active: production
  api.base.url: http://localhost:30001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: db
    application: db-service
    system: springboot-sample
  name: db
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-db
    application: db-service
    system: springboot-sample
  name: rest-db
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: rest-db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-git
    application: git-service
    system: springboot-sample
  name: rest-git
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: rest-git
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-backend
    application: backend
    system: springboot-sample
  name: rest-backend
spec:
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 30001
  selector:
    app: rest-backend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui-frontend
    application: frontend
    system: springboot-sample
  name: ui-frontend
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app: ui-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
    application: db-service
    system: springboot-sample
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        application: db-service
        name: db
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: db-config
          image: bitnami/postgresql:14
          name: db
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: db-data
            - mountPath: /docker-entrypoint-initdb.d
              name: db-init-data
      initContainers:
        - command:
            - sh
            - get-data.sh
          image: registry.access.redhat.com/ubi8-minimal:8.6
          name: get-data
          volumeMounts:
            - mountPath: /docker-entrypoint-preinitdb.d
              name: db-init
            - mountPath: /docker-entrypoint-initdb.d
              name: db-init-data
          workingDir: /docker-entrypoint-preinitdb.d
      volumes:
        - emptyDir: {}
          name: db-data
        - emptyDir: {}
          name: db-init-data
        - configMap:
            name: db-init
          name: db-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-db
    application: db-service
    system: springboot-sample
  name: rest-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-db
  template:
    metadata:
      labels:
        app: rest-db
        application: db-service
        system: springboot-sample
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: rest-db-config
            - secretRef:
                name: rest-db-config-creds
          image: springboot/rest-db-jvm:latest
          imagePullPolicy: IfNotPresent
          name: rest-db
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-git
    application: git-service
    system: springboot-sample
  name: rest-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-git
  template:
    metadata:
      labels:
        app: rest-git
        application: git-service
        system: springboot-sample
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: rest-git-config
          image: springboot/rest-git-jvm:latest
          imagePullPolicy: IfNotPresent
          name: rest-git
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-backend
    application: backend
    system: springboot-sample
  name: rest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-backend
  template:
    metadata:
      labels:
        app: rest-backend
        application: backend
        system: springboot-sample
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: rest-backend-config
          image: springboot/rest-backend-jvm:latest
          imagePullPolicy: IfNotPresent
          name: rest-backend
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui-frontend
    application: frontend
    system: springboot-sample
  name: ui-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-frontend
  template:
    metadata:
      labels:
        app: ui-frontend
        application: frontend
        system: springboot-sample
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: ui-frontend-config
          image: springboot/ui-frontend-jvm:latest
          imagePullPolicy: IfNotPresent
          name: ui-frontend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1