server:
  port: 8080
  address: 0.0.0.0

api:
  base:
    url: http://localhost:8083

spring:
  application:
    name: ui-frontend
  profiles:
    active: dev
  security:
    saml2:
      relyingparty:
        registration:
          auth0:
            assertingparty:
              metadata-uri: https://dev-i7btdyfxq64m44re.us.auth0.com/samlp/metadata/dGTb7mv3Z1VAttIb1uJSx5qoRPaaw4nA
            signing:
              credentials:
                - private-key-location: classpath:credentials/local.key
                  certificate-location: classpath:credentials/local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      app: ${spring.application.name}
      application: ${spring.application.name}
      system: springboot-sample

private:
  key: classpath:credentials/local.key
public:
  certificate: classpath:credentials/local.crt

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.saml2: TRACE
    org.springframework.security.authentication: TRACE
    org.springframework.security.authorization: TRACE
    org.springframework.security.web.csrf.CsrfFilter: DEBUG
    org.opensaml: INFO
    org.opensaml.saml: TRACE

