server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: rest-db
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      app: ${spring.application.name}
      application: ${spring.application.name}
      system: springboot-sample